/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "haptic": {
    name: "haptic",
    description: "Trigger haptic feedback on mobile devices.",
    type: "registry:lib",
    files: [{
      path: "src/registry/lib/haptic/haptic.ts",
      type: "registry:lib",
      target: "@lib/haptic.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/haptic/haptic.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "haptic"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "use-sound": {
    name: "use-sound",
    description: "Hook for playing sound effects with volume, playback rate, and interrupt controls.",
    type: "registry:hook",
    files: [{
      path: "src/registry/hooks/sound/use-sound.ts",
      type: "registry:hook",
      target: "@hooks/sound/use-sound.ts",
    },{
      path: "src/registry/lib/sound/sound-engine.ts",
      type: "registry:lib",
      target: "@lib/sound/sound-engine.ts",
    },{
      path: "src/registry/lib/sound/sound-types.ts",
      type: "registry:lib",
      target: "@lib/sound/sound-types.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/sound/use-sound.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-sound"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "text-flip": {
    name: "text-flip",
    description: "Animated text that cycles through items with a smooth flip transition.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/text-flip/text-flip.tsx",
      type: "registry:component",
      target: "@components/text-flip.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/text-flip/text-flip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "text-flip"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "chevrons-up-down-icon": {
    name: "chevrons-up-down-icon",
    description: "Animated chevrons icon that morphs between up and down directions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx",
      type: "registry:component",
      target: "@components/chevrons-up-down-icon.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "chevrons-up-down-icon"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "testimonial": {
    name: "testimonial",
    description: "Display user feedback with author info, avatar, and verified badge.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial/testimonial.tsx",
      type: "registry:component",
      target: "@components/testimonial.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial/testimonial.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonial"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "Copy text to clipboard with visual, haptic, and audio feedback.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/copy-button/copy-button.tsx",
      type: "registry:component",
      target: "@components/copy-button.tsx",
    },{
      path: "src/hooks/use-copy-to-clipboard.ts",
      type: "registry:hook",
      target: "@hooks/use-copy-to-clipboard.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/copy-button/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "copy-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "testimonial-spotlight": {
    name: "testimonial-spotlight",
    description: "Testimonial card with spotlight effect on hover.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial-spotlight/testimonial-spotlight.tsx",
      type: "registry:component",
      target: "@components/testimonial-spotlight.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial-spotlight/testimonial-spotlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonial-spotlight"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "glow-card-grid": {
    name: "glow-card-grid",
    description: "Display cards with glowing border and background effects.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/glow-card-grid/glow-card-grid.tsx",
      type: "registry:component",
      target: "@components/glow-card-grid.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/glow-card-grid/glow-card-grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "glow-card-grid"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "middle-truncation": {
    name: "middle-truncation",
    description: "Truncate text in the middle while preserving start and end.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/middle-truncation/middle-truncation.tsx",
      type: "registry:component",
      target: "@components/middle-truncation.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/middle-truncation/middle-truncation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "middle-truncation"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "twemoji": {
    name: "twemoji",
    description: "Render Unicode emoji as Twemoji SVG images inline with text.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/twemoji/twemoji.tsx",
      type: "registry:component",
      target: "@components/twemoji.tsx",
    },{
      path: "src/registry/components/twemoji/lib/twemoji-regex.ts",
      type: "registry:lib",
      target: "@lib/twemoji-regex.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/twemoji/twemoji.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "twemoji"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "contribution-graph": {
    name: "contribution-graph",
    description: "A GitHub-style contribution graph component that displays activity levels over time.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/contribution-graph/contribution-graph.tsx",
      type: "registry:component",
      target: "@components/contribution-graph.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/contribution-graph/contribution-graph.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "contribution-graph"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "github-contributions": {
    name: "github-contributions",
    description: "Visualize year-long GitHub contribution activity with daily counts, tooltips, and a profile link.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/github-contributions/github-contributions.tsx",
      type: "registry:component",
      target: "@components/github-contributions.tsx",
    },{
      path: "src/registry/components/github-contributions/lib/get-cached-contributions.ts",
      type: "registry:lib",
      target: "@lib/get-cached-contributions.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/github-contributions/github-contributions.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "github-contributions"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "icon-swap": {
    name: "icon-swap",
    description: "Animate icon swaps with scale, blur, and fade transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/icon-swap/icon-swap.tsx",
      type: "registry:component",
      target: "@components/icon-swap.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/icon-swap/icon-swap.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "icon-swap"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "spinning-circular-text": {
    name: "spinning-circular-text",
    description: "Text arranged in a circle with a continuous spinning animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/spinning-circular-text/spinning-circular-text.tsx",
      type: "registry:component",
      target: "@components/spinning-circular-text.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/spinning-circular-text/spinning-circular-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "spinning-circular-text"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "logos-carousel": {
    name: "logos-carousel",
    description: "Cycle through logos column by column in a staggered wave.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/logos-carousel/logos-carousel.tsx",
      type: "registry:component",
      target: "@components/logos-carousel.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/logos-carousel/logos-carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logos-carousel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "testimonial-2": {
    name: "testimonial-2",
    description: "Display a testimonial quote with author attribution and source link.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/testimonial-2/testimonial-2.tsx",
      type: "registry:component",
      target: "@components/testimonial-2.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/testimonial-2/testimonial-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonial-2"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "timescale": {
    name: "timescale",
    description: "Ruler-style timeline for plotting milestones along a horizontal or vertical axis.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/timescale/timescale.tsx",
      type: "registry:component",
      target: "@components/timescale.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/timescale/timescale.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timescale"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "work-experience": {
    name: "work-experience",
    description: "Display work experiences with role details, company logos, and durations.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/work-experience/work-experience.tsx",
      type: "registry:component",
      target: "@components/work-experience.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/work-experience/work-experience.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "work-experience"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: undefined,
  },
  "dot-grid-spotlight": {
    name: "dot-grid-spotlight",
    description: "Interactive dot grid with a cursor-tracking spotlight effect.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/dot-grid-spotlight/dot-grid-spotlight.tsx",
      type: "registry:component",
      target: "@components/dot-grid-spotlight.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/dot-grid-spotlight/dot-grid-spotlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dot-grid-spotlight"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "login-01": {
    name: "login-01",
    description: "A simple login form.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/login-01/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx",
    },{
      path: "src/registry/blocks/login-01/components/login-form.tsx",
      type: "registry:component",
      target: "@components/login-form.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/login-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "login-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["application"],
    meta: {"createdAt":"2026-02-22"},
  },
  "hero-01": {
    name: "hero-01",
    description: "A hero section with a golden spiral background.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/hero-01/hero-01.tsx",
      type: "registry:component",
      target: "@components/hero-01.tsx",
    },{
      path: "src/registry/blocks/hero-01/components/hero-01-icons.tsx",
      type: "registry:component",
      target: "@components/hero-01-icons.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/hero-01/hero-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "hero-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-12"},
  },
  "blog-01": {
    name: "blog-01",
    description: "A blog section with a grid layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/blog-01/blog-01.tsx",
      type: "registry:component",
      target: "@components/blog-01.tsx",
    },{
      path: "src/registry/blocks/blog-01/components/article-item.tsx",
      type: "registry:component",
      target: "@components/article-item.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/blog-01/blog-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "blog-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-13"},
  },
  "blog-02": {
    name: "blog-02",
    description: "A blog section with a lined grid layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/blog-02/blog-02.tsx",
      type: "registry:component",
      target: "@components/blog-02.tsx",
    },{
      path: "src/registry/blocks/blog-02/components/article-item.tsx",
      type: "registry:component",
      target: "@components/article-item.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/blog-02/blog-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "blog-02"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-18"},
  },
  "testimonials-01": {
    name: "testimonials-01",
    description: "A testimonials section with dual marquees.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/testimonials-01/testimonials-01.tsx",
      type: "registry:component",
      target: "@components/testimonials-01.tsx",
    },{
      path: "src/registry/blocks/testimonials-01/components/testimonial-list.tsx",
      type: "registry:component",
      target: "@components/testimonial-list.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonials-01/testimonials-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonials-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-20","previewClassName":"container mx-auto min-h-svh content-center-safe"},
  },
  "testimonials-02": {
    name: "testimonials-02",
    description: "A testimonials section with a lined layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/testimonials-02/testimonials-02.tsx",
      type: "registry:component",
      target: "@components/testimonials-02.tsx",
    },{
      path: "src/registry/blocks/testimonials-02/components/testimonial-list.tsx",
      type: "registry:component",
      target: "@components/testimonial-list.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonials-02/testimonials-02.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonials-02"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-29","previewClassName":"min-h-svh content-center-safe"},
  },
  "experience-01": {
    name: "experience-01",
    description: "A work experience section with a lined layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/experience-01/experience-01.tsx",
      type: "registry:component",
      target: "@components/experience-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/experience-01/experience-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "experience-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-28"},
  },
  "team-01": {
    name: "team-01",
    description: "A team section with glowing cards.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/team-01/team-01.tsx",
      type: "registry:component",
      target: "@components/team-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/team-01/team-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "team-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-03-30","previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "metrics-01": {
    name: "metrics-01",
    description: "A metrics section with a line chart.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/metrics-01/metrics-01.tsx",
      type: "registry:component",
      target: "@components/metrics-01.tsx",
    },{
      path: "src/registry/blocks/metrics-01/components/metric.tsx",
      type: "registry:component",
      target: "@components/metric.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/metrics-01/metrics-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "metrics-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-05-24","previewClassName":"min-h-svh content-center-safe"},
  },
  "social-links-01": {
    name: "social-links-01",
    description: "A social links section with a lined grid layout.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/social-links-01/social-links-01.tsx",
      type: "registry:component",
      target: "@components/social-links-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/social-links-01/social-links-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "social-links-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-06-16","previewClassName":"min-h-svh content-center-safe"},
  },
  "social-proof-01": {
    name: "social-proof-01",
    description: "A social proof section with a logos carousel.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/social-proof-01/social-proof-01.tsx",
      type: "registry:component",
      target: "@components/social-proof-01.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/social-proof-01/social-proof-01.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "social-proof-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["marketing"],
    meta: {"createdAt":"2026-06-26","previewClassName":"min-h-svh content-center-safe"},
  },
  "not-found-01": {
    name: "not-found-01",
    description: "A 404 page with a playable brick breaker game.",
    type: "registry:block",
    files: [{
      path: "src/registry/blocks/not-found-01/page.tsx",
      type: "registry:page",
      target: "app/not-found.tsx",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/index.tsx",
      type: "registry:component",
      target: "@components/daikanoid/index.tsx",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/component.tsx",
      type: "registry:component",
      target: "@components/daikanoid/component.tsx",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/ball.ts",
      type: "registry:component",
      target: "@components/daikanoid/ball.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/brick.ts",
      type: "registry:component",
      target: "@components/daikanoid/brick.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/paddle.ts",
      type: "registry:component",
      target: "@components/daikanoid/paddle.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/logos.ts",
      type: "registry:component",
      target: "@components/daikanoid/logos.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/colors.ts",
      type: "registry:component",
      target: "@components/daikanoid/colors.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/constants.ts",
      type: "registry:component",
      target: "@components/daikanoid/constants.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/types.ts",
      type: "registry:component",
      target: "@components/daikanoid/types.ts",
    },{
      path: "src/registry/blocks/not-found-01/components/daikanoid/ui.ts",
      type: "registry:component",
      target: "@components/daikanoid/ui.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/not-found-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "not-found-01"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["application"],
    meta: {"createdAt":"2026-08-09"},
  },
  "text-flip-demo": {
    name: "text-flip-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/text-flip-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/text-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "text-flip-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonial-demo": {
    name: "testimonial-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonial-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/copy-button-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/copy-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "copy-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "haptic-demo": {
    name: "haptic-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/haptic-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/haptic-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "haptic-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "testimonial-spotlight-demo": {
    name: "testimonial-spotlight-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-spotlight-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-spotlight-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonial-spotlight-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "glow-card-grid-demo": {
    name: "glow-card-grid-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glow-card-grid-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/glow-card-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "glow-card-grid-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "glow-card-grid-dialkit": {
    name: "glow-card-grid-dialkit",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/glow-card-grid-dialkit.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/glow-card-grid-dialkit.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "glow-card-grid-dialkit"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: {"previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "middle-truncation-demo": {
    name: "middle-truncation-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/middle-truncation-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/middle-truncation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "middle-truncation-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "twemoji-demo": {
    name: "twemoji-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/twemoji-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/twemoji-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "twemoji-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "theme-toggle-effect-demo": {
    name: "theme-toggle-effect-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/theme-toggle-effect-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/theme-toggle-effect-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "theme-toggle-effect-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-demo": {
    name: "github-contributions-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "github-contributions-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-default-theme": {
    name: "github-contributions-default-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-default-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-default-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "github-contributions-default-theme"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-winter-theme": {
    name: "github-contributions-winter-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-winter-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-winter-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "github-contributions-winter-theme"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-halloween-theme": {
    name: "github-contributions-halloween-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-halloween-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-halloween-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "github-contributions-halloween-theme"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "icon-swap-demo": {
    name: "icon-swap-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/icon-swap-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/icon-swap-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "icon-swap-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spinning-circular-text-demo": {
    name: "spinning-circular-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spinning-circular-text-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/spinning-circular-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "spinning-circular-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spinning-circular-text-demo-2": {
    name: "spinning-circular-text-demo-2",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/spinning-circular-text-demo-2.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/spinning-circular-text-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "spinning-circular-text-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chevrons-up-down-icon-demo": {
    name: "chevrons-up-down-icon-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/chevrons-up-down-icon-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/chevrons-up-down-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "chevrons-up-down-icon-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "logos-carousel-demo": {
    name: "logos-carousel-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/logos-carousel-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/logos-carousel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "logos-carousel-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: {"previewClassName":"min-h-svh place-items-center-safe content-center-safe"},
  },
  "testimonial-2-demo": {
    name: "testimonial-2-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/testimonial-2-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/testimonial-2-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "testimonial-2-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "timescale-demo": {
    name: "timescale-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/timescale-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/timescale-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "timescale-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}